Repository meilisearch/gatsby-plugin-meilisearch, pull requests merged in 2022-01, with the labels that each got.

#92 Add jsdoc
  gatsby-node.js
  src/validate.js
Labels: documentation

#91 Add more explanation on readme about how it works
  README.md
Labels: documentation, Blocked

#105 Ignore dev dependencies dependabot updates
  .github/dependabot.yml
Labels: skip-changelog

#107 Improve api keys documentation in readme
  README.md
Labels: documentation, skip-changelog
